//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNSWeb {
	
	
	public partial class Order {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HiddenField pageFadeOut;
		
		protected System.Web.UI.WebControls.HiddenField pageFadeIn;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl orderTableTitle;
		
		protected System.Web.UI.WebControls.Table ordersTable;
		
		protected System.Web.UI.WebControls.TableRow cakeRow;
		
		protected System.Web.UI.WebControls.TableRow cupcakeRow;
		
		protected System.Web.UI.WebControls.TableRow cheesecakeRow;
		
		protected System.Web.UI.WebControls.TableRow cookiesRow;
		
		protected System.Web.UI.WebControls.Table orderDetailsTable;
		
		protected System.Web.UI.WebControls.TableRow occasionRow;
		
		protected System.Web.UI.WebControls.Label occasionLbl;
		
		protected System.Web.UI.WebControls.DropDownList occasionDdl;
		
		protected System.Web.UI.WebControls.Button addItemBtn;
		
		protected System.Web.UI.WebControls.Button doneBtn;
		
		protected System.Web.UI.WebControls.Button checkOutBtn;
	}
}
