//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNSWeb {
	
	
	public partial class Order {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Table ordersTable;
		
		protected System.Web.UI.WebControls.DropDownList occasionDdl;
		
		protected System.Web.UI.WebControls.DropDownList desertTypeDdl;
		
		protected System.Web.UI.WebControls.RadioButton radioBtnYes;
		
		protected System.Web.UI.WebControls.RadioButton radioBtnNo;
		
		protected System.Web.UI.WebControls.DropDownList servingSizeDdl;
		
		protected System.Web.UI.WebControls.DropDownList DesertFlavorDdl;
		
		protected System.Web.UI.WebControls.DropDownList frostingFlavorDdl;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea foodAlergiesTextArea;
		
		protected System.Web.UI.WebControls.Table confTable;
		
		protected System.Web.UI.WebControls.Button addItemBtn;
		
		protected System.Web.UI.WebControls.Button doneBtn;
		
		protected System.Web.UI.WebControls.Button checkOutBtn;
		
		protected System.Web.UI.WebControls.HiddenField hiddenField;
		
		protected System.Web.UI.WebControls.HiddenField hiddenField1;
	}
}
